#!/bin/sh
#
# @name Gazebo Flying Car
#
# @type Flying Car
# @class Experimental
#

. ${R}etc/init.d/rc.flying_car_sitl_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=flying_car}

param set-default SIM_GZ_EN 1
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_R_REV 48

param set-default CA_ROTOR0_PX  0.225
param set-default CA_ROTOR0_PY  0.225
param set-default CA_ROTOR0_KM  0.05
param set-default CA_ROTOR1_PX -0.225
param set-default CA_ROTOR1_PY -0.225
param set-default CA_ROTOR1_KM  0.05
param set-default CA_ROTOR2_PX  0.225
param set-default CA_ROTOR2_PY -0.225
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.225
param set-default CA_ROTOR3_PY  0.225
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

# The wheel bridge owns a compact two-channel array. These functions select
# flying-car Motor5/Motor6 while the model-side actuator indices remain 0/1.
param set-default SIM_GZ_WH_FUNC1 105
param set-default SIM_GZ_WH_MIN1 80
param set-default SIM_GZ_WH_MAX1 120
param set-default SIM_GZ_WH_DIS1 100
param set-default SIM_GZ_WH_FUNC2 106
param set-default SIM_GZ_WH_MIN2 80
param set-default SIM_GZ_WH_MAX2 120
param set-default SIM_GZ_WH_DIS2 100
