#!/bin/sh
#
# @name Fully Actuated Hexarotor x
#
# @type Hexarotor x
# @class Copter
#

# Gazebo wrapper for 6003_fully_actuated_hexa.
# QGC airframe UI / CA geometry / FA defaults come from the real airframe.
PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=fully_actuated_hexa}

. ${R}etc/init.d/airframes/6003_fully_actuated_hexa

param set-default SIM_GZ_EN 1

# The GZ bridge publishes synthetic ESC telemetry from motor-speed commands,
# but this model has no real ESC arming feedback/current telemetry.
param set-default COM_ARM_CHK_ESCS 0
param set-default FD_ESCS_EN 0

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MIN6 0

param set-default SIM_GZ_EC_MAX1 1600
param set-default SIM_GZ_EC_MAX2 1600
param set-default SIM_GZ_EC_MAX3 1600
param set-default SIM_GZ_EC_MAX4 1600
param set-default SIM_GZ_EC_MAX5 1600
param set-default SIM_GZ_EC_MAX6 1600

# Gazebo applies thrust proportional to rotor speed squared; keep inverse
# square-root mapping (also defaulted in 6003 as THR_MDL_FAC 1.0).
param set-default THR_MDL_FAC 1.0

param set-default NAV_DLL_ACT 2
