#!/bin/sh
#
# @name Flying Car (Quadrotor + Differential Drive)
#
# @type Flying Car
# @class Experimental
#
# @output Motor1 front right rotor
# @output Motor2 rear left rotor
# @output Motor3 front left rotor
# @output Motor4 rear right rotor
# @output Motor5 left wheel
# @output Motor6 right wheel
#

. ${R}etc/init.d/rc.flying_car_defaults

# Native quad allocation owns Motor1-4; the flying-car gate owns Motor1-6.
param set-default SYS_FC_TYPE 1
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_R_REV 48

# Square quadrotor X geometry in PX4 FRD coordinates.
param set-default CA_ROTOR0_PX  0.225
param set-default CA_ROTOR0_PY  0.225
param set-default CA_ROTOR0_KM  0.05
param set-default CA_ROTOR1_PX -0.225
param set-default CA_ROTOR1_PY -0.225
param set-default CA_ROTOR1_KM  0.05
param set-default CA_ROTOR2_PX  0.225
param set-default CA_ROTOR2_PY -0.225
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.225
param set-default CA_ROTOR3_PY  0.225
param set-default CA_ROTOR3_KM -0.05

# Pixhawk 6X AUX1-4 use DShot600; AUX5-6 use 50 Hz reversible PWM.
param set-default PWM_AUX_TIM0 -3
param set-default PWM_AUX_TIM1 50
param set-default PWM_AUX_FUNC1 101
param set-default PWM_AUX_FUNC2 102
param set-default PWM_AUX_FUNC3 103
param set-default PWM_AUX_FUNC4 104
param set-default PWM_AUX_FUNC5 105
param set-default PWM_AUX_FUNC6 106

# Reversible wheel ESC neutral and calibrated range.
param set-default PWM_AUX_DIS5 1500
param set-default PWM_AUX_MIN5 1100
param set-default PWM_AUX_MAX5 1900
param set-default PWM_AUX_DIS6 1500
param set-default PWM_AUX_MIN6 1100
param set-default PWM_AUX_MAX6 1900
